# Task 1

<b>1.1. Write a function to compute 5/0 and use try/except to catch the exceptions.</b>

In [4]:
def divison_by_zero():
    return 5/0

try:
    divison_by_zero()
except:
    print("Error: 5 is not didisible by zero.")
    

Error: 5 is not didisible by zero.


<b>1.2. Implement a Python program to generate all sentences where subject is in ["Americans",
"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].</b>
<pre>Hint: Subject,Verb and Object should be declared in the program as shown below.
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

<b>Output should come as below:</b>
Americans play Baseball.
Americans play Cricket.
Americans watch Baseball.
Americans watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket.
</pre>

In [7]:
subjects=["Americans","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

def make_sentense(subjects, verbs, objects):
    return [(sub + " " + vb + " " + obj + ".") for sub in subjects for vb in verbs for obj in objects]

sentenses = make_sentense(subjects, verbs, objects)

for sen in sentenses:
    print(sen)

Americans play Baseball.
Americans play Cricket.
Americans watch Baseball.
Americans watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket.


# Task 2

<b>2.1 Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.</b> <br>
<b>HINT:</b> Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde.


In [54]:
import numpy as np

def generate_matrix(vector,n=0,increasing=True):
    # make the n value as the size of the vector
    n = (n==0) and vector.size or n
        
    if increasing:
        output = np.array([x**i for x in vector for i in range(n)]).reshape(vector.size,n)
    elif not increasing:
        output = np.array([x**(n-1-i) for x in vector for i in range(n)]).reshape(vector.size,n)
    
    return output

input_vector = np.array([1,2,3,4,5])
print(generate_matrix(input_vector))
print("------------------------------------------------")
print(generate_matrix(input_vector, 6))
print("------------------------------------------------")
print(generate_matrix(input_vector, increasing=False))
print("------------------------------------------------")
print(generate_matrix(input_vector, 8, increasing=False))
print("------------------------------------------------")
print(generate_matrix(input_vector, 3, increasing=False))
print("------------------------------------------------")
print(generate_matrix(input_vector, 3))
print("------------------------------------------------")

[[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]]
------------------------------------------------
[[   1    1    1    1    1    1]
 [   1    2    4    8   16   32]
 [   1    3    9   27   81  243]
 [   1    4   16   64  256 1024]
 [   1    5   25  125  625 3125]]
------------------------------------------------
[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]
------------------------------------------------
[[    1     1     1     1     1     1     1     1]
 [  128    64    32    16     8     4     2     1]
 [ 2187   729   243    81    27     9     3     1]
 [16384  4096  1024   256    64    16     4     1]
 [78125 15625  3125   625   125    25     5     1]]
------------------------------------------------
[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]]
------------------------------------------------
[[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1